import Link from 'next/link'
import './globals.css'


export const metadata = {
  title: 'ste Next App',
  description: 'Generated by create next app',
  icons: {
    icon:'/images/favicon.png'
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <h1> <Link href="/">WEB</Link></h1>
        <ol>
          <li><Link href="/read/1">HTML</Link></li>
          <li><Link href="/read/2">CSS</Link></li>
          <li><Link href="/read/3">JS</Link></li>
        </ol>
        {children}
        <ul>
          <li><Link href="/create">CREATE</Link></li>
          <li><Link href="/update/1">UPDATE</Link></li>
          <li><input type="button" value="delete" /></li>
        </ul>
      </body>
    </html>
  )
}
